import React, { Component } from 'react';
import {
	AppRegistry,
	StyleSheet,
	Text,
	View,
	StatusBar
} from "react-native";
import {Actions } from 'react-native-router-flux';

import { Container, Header, Left, Icon, Body, Right, Button, Card, CardItem, Title, Footer, FooterTab, Content, List, ListItem, Fab } from 'native-base';
import Drawer from '../Drawer/Drawer';
import Notifications from '../Notifications/Notifications';
import config from "./../../config";


class DriverView extends Component {
	//this is the main driver page where you can see the rides you have posted

	constructor(props){
		super(props);
		this.address = config.ip
		this.openMenu = this.openMenu.bind(this);
		this.openNotifications = this.openNotifications.bind(this);
		this.baseUrl = "http://" + this.address + ":3000/";
		this.state = {
			data: []
		}
	}

	openNotifications(){
		this.notifications.openDrawer();
	}

	openMenu() {
		this.drawer.openDrawer();
	}


	postButton(){
		let resObj = this.props.resObj;
		Actions.ridePosting({resObj});
	}

	retrievePosts(){
		return fetch(this.baseUrl + this.props.resObj.email + '/driverView', {
			method: "GET"
		})
		.then((response) => {
			if(response.status === 200) {
				resObjPromise = response.json();

				resObjPromise.then((resObj) => {
					let rydeIds = resObj;
					let dataSet = [];
					// loop over the array and then make get requests based on the rydeId
					for (let i = 0; i < rydeIds.length; ++i) {
						// asynchronous calls in a for loop are controlled
						fetch(this.baseUrl + rydeIds[i] + "/populateDriverView").then((res) => {
							if (res.status === 200) {
								// obtains the promise generated by res.json()
								let resObjPromise = res.json();
								resObjPromise.then((resObj) => {
									dataSet.push(
										<View key={i}>
											<CardItem style={{marginBottom: 20, marginLeft: 5, marginRight: 5, backgroundColor: 'rgb(72, 110, 255)'}} button onPress={() => Actions.driverRideProfile({resObjRide, resObjDriver})}>
												<Body>
													<Text style={{color: '#fff'}}>From: {resObj.from}</Text>
													<Text style={{color: '#fff'}}>To: {resObj.to}</Text>
													<Text style={{color: '#fff'}}>Date: {resObj.date}</Text>
													<Text style={{color: '#fff', left: 275}}>Price: ${resObj.price}</Text>
												</Body>
											</CardItem>
										</View>
									);
									// everytime we append something to the dataSet in the loop
									// we set the state inside the promise .then function as it is async
									this.setState({data: dataSet});
								});
							} else {
								alert("Server error");
							}
						}, (err) => {
							alert(err)
						});
					}
				});
			}
		}, (err) => {
			alert(err)
		});
	}

	componentDidMount(){
		this.retrievePosts();
	}

	render() {
		//retrieve data from the db and then add the reqobj in to an array and then push this array in to lists, and create the list.
		let resObj = this.props.resObj;

		return (
			<Notifications
				ref={(notifications) => (this.notifications = notifications)}>
				<Drawer
					ref={(drawer) => this.drawer = drawer}>
					<Container>
						<Header style={{backgroundColor: 'rgb(72, 110, 255)'}}>
							<StatusBar
								backgroundColor="rgb(72, 110, 255)"
								barStyle="light-content"
								hidden = {false}
								/>
							<Left style = {{flex: 1}}>
								<Button transparent onPress={this.openMenu}>
									<Icon name='menu' />
								</Button>
							</Left>
							<Body style={{flex: 1}}>
								<Title style={{fontFamily: 'sans-serif'}}>DASHBOARD</Title>
							</Body>
							<Right style = {{flex: 1}}>
								<Button onPress = {() => {this.openNotifications()}} transparent>
									<Icon name='notifications' />
								</Button>
							</Right>
						</Header>
						<View style={{paddingBottom: 20, backgroundColor: '#fff'}} />
						<Content style={{backgroundColor: '#fff'}}>
							{this.state.data}
						</Content>
						<View>
							<Fab
								active={this.state.active}
								direction="up"
								containerStyle={{ }}
								style={{ backgroundColor: 'rgb(72, 110, 255)' }}
								position="bottomRight"
								onPress={() => {this.postButton()}}>
								<Icon name="add" />
							</Fab>
						</View>
					</Container>
				</Drawer>
			</Notifications>
		);
	}
}

const styles = StyleSheet.create({
	text: {
		color: 'white',
		fontSize: 16,
	},

	flatlist: {
		marginTop: 25,

		flex: 1
	},

	price: {
		marginRight: 15,
		textAlign: 'right'

	}
});

module.exports = DriverView;

AppRegistry.registerComponent("DriverView", () => DriverView);
